### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by kevin-zhan** [blackjack0v0/easyupload#1]
会写代码的医学生超屌呀！
不过直接在github里面把医院相关的api全部暴露出来不是很好吧。如果被有心人看到，很容易拿去攻击医院网络，获取病人等各类敏感信息。（这类公共部门的网址安全度非常低，不管是ddos还是直接撞库都很容易造成影响）

**Comment by blackjack0v0** [comment]
多谢提醒！！！之前没注意到这个问题，因为所有接口都是通过网页抓包的获取的，同时这个是独立于医院的外部的网络，所以就没有考虑到要把地址隐藏起来。我中午回去就修改一下！

**Comment by blackjack0v0** [comment]
已经修改好啦，再次感谢提醒！！ @kevin-zhan
